/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    BottomFloatingBar: typeof import('./components/BottomFloatingBar.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialMediaCarousek: typeof import('./components/index/SocialMediaCarousek.vue')['default']
    SocialMediaCarousel: typeof import('./components/index/SocialMediaCarousel.vue')['default']
    SocialMediaCarouselItem: typeof import('./components/index/SocialMediaCarouselItem.vue')['default']
    TopicCarouselItem: typeof import('./components/index/TopicCarouselItem.vue')['default']
    WorkInProgressDisclaimer: typeof import('./components/WorkInProgressDisclaimer.vue')['default']
  }
}
